spring:
  datasource:
    url: jdbc:mysql://localhost:{ DB_PORT }/{ DB_DATABASE }?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: { DB_USERNAME }
    password: { DB_PASSWORD }

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher